num_cols:
  - 'Age'
  - 'RoomService'
  - 'FoodCourt'
  - 'ShoppingMall'
  - 'Spa'
  - 'VRDeck'

cat_cols:
  - 'HomePlanet'
  - 'Destination'

bool_cols:
  - 'CryoSleep'
  - 'VIP'

date_cols: []

useless_cols: []


target_cols:
    - 'Transported'
